apiVersion: v1
kind: Service
metadata:
 name: test-product2
spec:
 type: NodePort
 selector:
   app: test-app2
   env: prod2
 ports:
 - name: test2
   protocol: TCP
   port: 3300
   targetPort: 3300
   nodePort: 30002
